/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */

 // Dada a população inicial, porcentagem de crescimento por ano, delta (pessoas entrando e saindo)
 // e população alvo, retornar quantos anos a população demora a crescer.


//Markus
//Paulo S.
//Paulo M.
//Henrique
//Elisa
//Paulo S.

package populacao.dojo

import kotlin.test.Test
import kotlin.test.assertNotNull
import kotlin.test.assertEquals

class AppTest {
	@Test fun quantosAnos_1000_2_50_1200() {
		val populacaoInicial = 1000
        val porcentagemDeCrescimento = 2
        val novosImigrantes = 50
        val populacaoMeta = 1200

        val resultadoEsperado = 3
		val resultadoAnos = crescimentoPopulacional(
                                populacaoInicial, 
                                porcentagemDeCrescimento, 
                                novosImigrantes,
                                populacaoMeta
                            )

		assertEquals(resultadoEsperado, resultadoAnos)
	}

    @Test fun quantosAnos_1500_5_100_5000() {
		val populacaoInicial = 1500
        val porcentagemDeCrescimento = 5
        val novosImigrantes = 100
        val populacaoMeta = 5000

        val resultadoEsperado = 15
		val resultadoAnos = crescimentoPopulacional(
                                populacaoInicial, 
                                porcentagemDeCrescimento, 
                                novosImigrantes,
                                populacaoMeta
                            )

		assertEquals(resultadoEsperado, resultadoAnos)
	}

    @Test fun quantosAnos_1500000_2_5_10000_2000000() {
		val populacaoInicial = 1500000
        val porcentagemDeCrescimento = 2.5
        val novosImigrantes = 10000
        val populacaoMeta = 2000000

        val resultadoEsperado = 10
		val resultadoAnos = crescimentoPopulacional(
                                populacaoInicial, 
                                porcentagemDeCrescimento, 
                                novosImigrantes,
                                populacaoMeta
                            )

		assertEquals(resultadoEsperado, resultadoAnos)
	}
}
