name: Test
on:
  push:
    branches:
    - main
jobs:
  test:
    name: unit_tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: java
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'gradle'
    - name: run_test
      run: ./gradlew test
