name: PRM_test
on:
  push:
    branches:
    - main
jobs:
  test:
    name: deploy to staging
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Java JDK
      uses: actions/setup-java@v2.3.1
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: 'gradle'
    - name: run_unit_tests
      run: ./gradlew test 
    
